<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="4SHISH" failures="1" tests="1" name="Default test(failed)(failed)(failed)(failed)" time="16.519" errors="0" timestamp="2024-03-27T22:41:32 IST">
  <testcase classname="base" name="second" time="16.221">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;[×
This user is already invited by you].&amp;gt; but was:&amp;lt;[User has been invited].&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[×
This user is already invited by you].> but was:<[User has been invited].>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.Assert.assertEquals(Assert.java:107)
at taskTwo.RequestForgetPassword(taskTwo.java:70)
at base.second(base.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- second -->
</testsuite> <!-- Default test(failed)(failed)(failed)(failed) -->
